# Generated by Django 3.1.2 on 2020-11-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='currentcity',
            field=models.CharField(default='San Fransisco', max_length=100),
            preserve_default=False,
        ),
    ]
