# Generated by Django 3.1.2 on 2020-11-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20201102_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='/images/default-profile-img.png', upload_to='images/'),
        ),
    ]
