# Generated by Django 3.1.2 on 2020-11-03 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20201102_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='picture',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
