# Generated by Django 3.1.2 on 2020-11-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20201104_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='/images/default-profile-img.png', upload_to='images/'),
        ),
    ]
