# Generated by Django 3.1.2 on 2020-11-04 22:15

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_city_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, default='', editable=False, populate_from='City.name', unique=True),
            preserve_default=False,
        ),
    ]
