# Generated by Django 3.1.2 on 2020-11-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_auto_20201104_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(default='slug', null=True),
        ),
    ]
