# Generated by Django 3.1.2 on 2020-11-05 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_profile_slug'),
        ('main_app', '0013_auto_20201104_0711'),
    ]

    operations = [
    ]
