# Generated by Django 3.1.2 on 2020-11-05 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date']},
        ),
    ]
