# Generated by Django 3.1.3 on 2020-11-06 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_merge_20201105_1113'),
        ('main_app', '0026_post_picture'),
    ]

    operations = [
    ]
