# Generated by Django 3.1.2 on 2020-11-06 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_post_picture'),
        ('main_app', '0023_merge_20201105_0808'),
    ]

    operations = [
    ]
