# Generated by Django 3.1.3 on 2020-11-06 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_merge_20201105_1605'),
        ('main_app', '0027_merge_20201105_1609'),
    ]

    operations = [
    ]
