# Generated by Django 3.1.2 on 2020-11-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_merge_20201105_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='picture',
            field=models.ImageField(blank=True, default='/images/default-profile-img.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, default='/images/default-profile-img.png', upload_to='images/'),
        ),
    ]
