# Generated by Django 3.1.2 on 2020-11-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0029_auto_20201105_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='picture',
            field=models.ImageField(blank=True, default='/images/shea-rouda-Vtl6cOhO87Y-unsplash.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, default='/images/florian-klauer-mk7D-4UCfmg-unsplash.jpg', upload_to='images/'),
        ),
    ]
