# Generated by Django 3.1.3 on 2020-11-06 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0030_auto_20201105_2306'),
        ('main_app', '0029_auto_20201105_2221'),
    ]

    operations = [
    ]
