# Generated by Django 3.1.3 on 2020-12-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0032_auto_20201223_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='static/images/default-profile-img.png', upload_to='static/images/'),
        ),
    ]
