# Generated by Django 3.1.3 on 2020-12-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0034_auto_20201223_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, default='/images/default.jpg', upload_to='images/'),
        ),
    ]
